# Generated by Django 5.2.1 on 2025-05-17 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.DateField()),
                ('state', models.CharField(choices=[('Andaman Nocobar Island', 'Andaman Nocobar Island'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Asam', 'Asam'), ('Bihar', 'Bihar'), ('Chandigarh', 'Chandigarh'), ('Chhatichgarh', 'Chhatichgarh'), ('Dadra & Nagar Haveli', 'Dadra & Nagar Haveli'), ('Dama & Due', 'Dama & Due'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('Gujurat', 'Gujurat'), ('Haryana', 'Haryana'), ('Himanchal Pradesh', 'Himanchal Pradesh'), ('jammu & Kashmir', 'jammu & Kashmir'), ('Jharakhand', 'Jharakhand'), ('Karnatak', 'Karnatak'), ('Keral', 'Keral'), ('lakshadweep', 'lakshadweep'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharastra', 'Maharastra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Pundicherry', 'Pundicherry'), ('Panjab', 'Panjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('tamil Nadu', 'tamil Nadu'), ('Telengana', 'Telengana'), ('Tripura', 'Tripura'), ('Utarakhand', 'Utarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('West Bengal', 'West Bengal')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
