# Generated by Django 5.2.1 on 2025-05-18 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_customer_zipcode_customer_bandacode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='bandacode',
            new_name='zipcode',
        ),
    ]
