# Generated by Django 5.2.1 on 2025-05-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_bandacode_customer_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='someone@gamil.com'),
        ),
    ]
