# Generated by Django 5.2.1 on 2025-05-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cart_quantity_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'on The Way'), ('Delivered', 'Delivered'), ('Caneled', 'Caneled'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
